name: e2e-tests-olm
description: Runs E2E tests against the OLM bundle
on:
  pull_request:

    branches:
    - v1alpha1

env:
  KIND_VERSION: "0.15.0"
  GO111MODULE: "on"
  OPERATOR_IMG: "quay.io/sustainable_computing_io/kepler-operator"
  KUBECONFIG: /tmp/.kube/config
  BUNDLE_IMG: "quay.io/sustainable_computing_io/kepler-operator-bundle"
 

jobs:
  e2e:
    name: build-operator
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_provider: [kind, microshift]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@main
        with: 
          go-version-file: go.mod


      - name: Use kepler action for kind cluster build
        uses: sustainable-computing-io/kepler-action@v0.0.1
        with:
          runningBranch: ${{matrix.cluster_provider}}
          cluster_provider: ${{matrix.cluster_provider}}

      - name: Install tools
        run: |
          chmod +x tests/run-e2e.sh
          ./test/run-e2e.sh tools_install
          
      - name: Build operator images
        shell: bash
        run: |
          ./test/run-e2e.sh build

      - name: Deploy operator
        run: |
          export CLUSTER_PROVIDER=${{matrix.cluster_provider}} && make prepareKubeConfig
          ./tests/run-e2e.sh deploy
          
      - name: Run e2e script
        shell: bash
        run: ./test/run-e2e.sh test_bundle

      - name: Clean up after e2e
        shell: bash
        run: ./test/run-e2e.sh bundle_cleanup
    

  e2e-success:
    name: Successful e2e tests
    needs: [e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        run: echo "Previous steps were successful"

#TO-DO
# Add tests for e2e that checks if all the kepler metrics are present
# kubectl wait --for=condition=Ready pod --all -n kepler-operator-system --timeout 3m
# - name: Setup tmate session
#         if: ${{ failure() }}
#         uses: mxschmitt/action-tmate@v3
